version: '3'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lavii@123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
