FROM node:14

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npm run build  # Add this line to compile TypeScript files

CMD ["node", "dist/server.js"]  # Assuming compiled JavaScript files are in the 'dist' directory
